################################### Default Configuration ############################
# baseurl = "https://demo.gethugothemes.com/vex/"
baseurl = "/"
title = "Vex | hugo landing page template"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# set default language
defaultContentLanguage = "fr"
