
###################################### Navigation english ######################################

[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Produits"
url = "products/"
weight = 2

[[main]]
name = "Media"
url = "blog/"
weight = 3

[[main]]
name = "Avis"
pre = "#"
url = "testimonial"
weight = 4

# footer menu
[[footer]]
name = "Media"
url = "blog/"
weight = 1

[[footer]]
name = "Terme & Conditions"
url = "terms-conditions/"
weight = 3

[[footer]]
name = "Conditions Générales"
url = "privacy-policy/"
weight = 4
