[build]
  publish = "public"
  command = "hugo --minify --gc"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_BASEURL = "/"
  MISE_PYTHON_COMPILE = "0"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY_PUBLIC,HUGO_SUPABASE_ANON_KEY_PUBLIC"

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}
